---
- name: Install AI Forge network configuration
  ansible.builtin.template:
    src: 90-ai-forge-network.yaml.j2
    dest: /etc/netplan/90-ai-forge-network.yaml
    owner: root
    group: root
    mode: "0600"
  no_log: true
  notify: Apply netplan

- name: Validate Netplan configuration
  ansible.builtin.command:
    cmd: netplan generate
  changed_when: false
