---
- name: Verify Ubuntu 24
  ansible.builtin.assert:
    that:
      - ansible_distribution == "Ubuntu"
      - ansible_distribution_major_version == "24"
    fail_msg: >-
      Expected Ubuntu 24, found
      {{ ansible_distribution }} {{ ansible_distribution_version }}

- name: Verify Netplan configuration
  ansible.builtin.stat:
    path: /etc/netplan/50-cloud-init.yaml
  register: os_network_config

- name: Require Netplan configuration
  ansible.builtin.assert:
    that:
      - os_network_config.stat.exists
    fail_msg: "Expected Ubuntu Netplan configuration not found"
