---
- name: Configure Daedalus model and inference runtime
  hosts: daedalus
  gather_facts: true
  become: true

  vars_files:
    - "../profiles/inference/{{ inference_profile }}.yaml"

  roles:
    - model
    - llama-runtime
