---
- name: Stage AI Forge networking
  hosts: daedalus
  gather_facts: true
  become: true

  vars_files:
    - ../../secrets/local.yaml

  roles:
    - role: ai-forge
      vars:
        ai_forge_stage: network
