---
llama_source_build:
  version: b10612
  commit: 7584430716ee229751771ed0d6bbcb780d105eeb
  configuration_id: arch-2026.09.01-amd64-cuda13.4-sm86-daedalus-01-native

  platform:
    distribution: Archlinux
    architecture: x86_64

  baseline: "2026.09.01"

  root: /opt/ai-forge/llama.cpp/b10612-cuda13.4-sm86

  cuda_architectures: "86"
  cpu_native: "ON"

  c_compiler: /usr/bin/gcc
  cxx_compiler: /usr/bin/g++
  cuda_compiler: /opt/cuda/bin/nvcc

  source_store: "{{ playbook_dir }}/../../../ai-stores/vault/github/ggml-org/llama.cpp/7584430716ee229751771ed0d6bbcb780d105eeb/source.git"
  ui_archive: "{{ playbook_dir }}/../../../ai-stores/vault/huggingface/buckets/ggml-org/llama-ui/b10612/dist.tar.gz"
  ui_sha256: 3f7a482b86620b5dfbaf3432927bd357e679440237d3d83c27c07423cecf1f6d

  pacman_repository: "http://10.10.10.1:81/ai-stores/vault/graystone/llama.cpp/dependencies/arch-cuda13.4-sm86/20260930T052629.926543Z/pacman"

  build_packages:
    - cuda
    - cmake
    - gcc
    - make
    - git
    - gzip
