---
llama_source_build:
  version: b10612
  commit: 7584430716ee229751771ed0d6bbcb780d105eeb
  configuration_id: arch-2026.09.01-amd64-cuda13.4-sm86-daedalus-01-native

  platform:
    distribution: Archlinux
    architecture: x86_64

  baseline: "2026.09.01"

  root: /opt/ai-forge/llama.cpp/b10612-cuda13.4-sm86

  cuda_architectures: "86"
  cpu_native: "ON"

  c_compiler: /usr/bin/gcc
  cxx_compiler: /usr/bin/g++
  cuda_compiler: /opt/cuda/bin/nvcc

  source_store: "{{ playbook_dir }}/../../../ai-stores/vault/github/ggml-org/llama.cpp/7584430716ee229751771ed0d6bbcb780d105eeb/source.git"
  ui_archive: "{{ playbook_dir }}/../../../ai-stores/vault/huggingface/buckets/ggml-org/llama-ui/b10612/dist.tar.gz"
  ui_sha256: 3f7a482b86620b5dfbaf3432927bd357e679440237d3d83c27c07423cecf1f6d

  pacman_repository: "http://10.10.10.1:81/ai-stores/vault/graystone/llama.cpp/dependencies/arch-cuda13.4-sm86/20260930T052629.926543Z/pacman"

  build_packages:
    - cuda
    - cmake
    - gcc
    - make
    - git
    - gzip

llama_prebuilt:
  version: b10612
  commit: 7584430716ee229751771ed0d6bbcb780d105eeb
  configuration_id: arch-2026.09.01-amd64-cuda13.4-sm86-daedalus-01-native

  root: /opt/ai-forge/llama.cpp/b10612-cuda13.4-sm86

  archive: "{{ playbook_dir }}/../../../ai-stores/vault/graystone/llama.cpp/b10612/arch-2026.09.01-amd64-cuda13.4-sm86-daedalus-01-native/20260930T061808Z-vvl1fi7b/llama-runtime.tar.gz"
  archive_sha256: 0f799c9e21b9262d4fb1ca4fb95bd2ec1b52063fd80a4a62e888d20f1be0672c

  distribution: Archlinux
  architecture: x86_64

  cpu_model: "11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz"
  gpu_name: "NVIDIA GeForce RTX 3090"
  compute_capability: "8.6"
  driver_version: "615.71.09"

  runtime_packages:
    glibc: "2.44+r50+g1848099f063e-1"
    openssl: "3.6.4-1"
    libgcc: "16.2.1+r23+gd564253eb6c8-1"
    libstdc++: "16.2.1+r23+gd564253eb6c8-1"
    libgomp: "16.2.1+r23+gd564253eb6c8-1"
    brotli: "1.2.0-1"
    zlib: "1:1.3.2-3"
    zstd: "1.5.7-3"
    nvidia-utils: "615.71.09-1"
