#!/usr/bin/env python3

from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parents[1]
MACHINES_DIR = ROOT / "machines"
OUTPUT_DIR = ROOT / "generated" / "dnsmasq"
OUTPUT_FILE = OUTPUT_DIR / "machines.conf"


def load_machines():
    machines = []

    for machine_file in sorted(MACHINES_DIR.glob("*/machine.yaml")):
        with machine_file.open("r", encoding="utf-8") as f:
            machine = yaml.safe_load(f)

        machines.append(machine)

    return machines


def validate(machines):
    names = set()
    ips = {}
    macs = {}

    for machine in machines:
        name = machine["name"]

        if name in names:
            raise RuntimeError(f"Duplicate machine name: {name}")
        names.add(name)

        network = machine.get("network", {})

        ip = network.get("provisioning_ip")
        mac = network.get("provisioning_mac")

        if ip:
            if ip in ips:
                raise RuntimeError(
                    f"Duplicate IP {ip}: {ips[ip]} and {name}"
                )
            ips[ip] = name

        if mac:
            mac = mac.lower()

            if mac in macs:
                raise RuntimeError(
                    f"Duplicate MAC {mac}: {macs[mac]} and {name}"
                )
            macs[mac] = name


def main():
    machines = load_machines()
    validate(machines)

    lines = [
        "# GENERATED BY GRAYSTONE AI FORGE - DO NOT EDIT",
        "",
    ]

    count = 0

    for machine in machines:
        network = machine.get("network", {})

        mac = network.get("provisioning_mac")
        ip = network.get("provisioning_ip")

        # Controllers such as Athena may have a fixed interface/IP
        # but no DHCP client MAC reservation.
        if not mac or not ip:
            continue

        lines.append(
            f"dhcp-host={mac},{ip},{machine['name']},12h"
        )
        count += 1

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"Generated {OUTPUT_FILE}")
    print(f"Reservations: {count}")


if __name__ == "__main__":
    main()
