"""Explicit NIC-to-loader policy; absent metadata retains legacy behavior."""
import ipaddress
import re
from pathlib import Path

KNOWN = {'1d6a:14c0': 'aqc1xx'}

def identity(machine):
    name = machine.get('name', '')
    if not isinstance(name, str) or not re.fullmatch(r'[a-z][a-z0-9]*(?:-[a-z0-9]+)*', name) or len(name) > 63:
        raise ValueError('Invalid machine name')
    net = machine.get('network') or {}
    pci = net.get('provisioning_pci_id')
    if pci is not None and (not isinstance(pci, str) or not re.fullmatch(r'[0-9a-f]{4}:[0-9a-f]{4}', pci)):
        raise ValueError('Invalid provisioning_pci_id')
    expected = KNOWN.get(pci, 'legacy')
    loader = net.get('provisioning_loader', expected)
    if loader != expected:
        raise ValueError(f'{name}: loader {loader!r} conflicts with PCI policy {expected}')
    mac = str(net.get('provisioning_mac', '')).lower()
    if mac and (not re.fullmatch(r'(?:[0-9a-f]{2}:){5}[0-9a-f]{2}', mac) or mac == '00:00:00:00:00:00' or int(mac[:2], 16) & 1):
        raise ValueError('Invalid provisioning MAC')
    if loader == 'aqc1xx' and (machine.get('architecture') != 'amd64' or not mac):
        raise ValueError('Native Aquantia requires amd64 and a provisioning MAC')
    ip = net.get('provisioning_ip')
    if ip:
        ipaddress.IPv4Address(ip)
    return {'name': name, 'mac': mac, 'pci_id': pci, 'loader': loader}


def report_pci(nic):
    vendors = re.findall(r'^PCI vendor: (0x[0-9a-fA-F]{4})$', nic, re.M)
    devices = re.findall(r'^PCI device: (0x[0-9a-fA-F]{4})$', nic, re.M)
    if len(vendors) != 1 or len(devices) != 1:
        raise ValueError('Selected NIC lacks unambiguous PCI IDs; collect a new report with updated inspect-hardware')
    return vendors[0][2:].lower() + ':' + devices[0][2:].lower()


def record_nic(network, pci):
    for key, value in [('provisioning_pci_id', pci), ('provisioning_loader', KNOWN.get(pci, 'legacy'))]:
        if key in network and network[key] != value:
            raise ValueError(f'Existing {key} conflicts with the hardware report')
        network[key] = value


def read_inventory(root):
    import yaml
    machines = []
    seen = {'name': set(), 'mac': set(), 'ip': set()}
    for path in sorted((root / 'machines').glob('*/machine.yaml')):
        m = yaml.safe_load(path.read_text())
        i = identity(m)
        if i['name'] != path.parent.name:
            raise ValueError('Inventory directory/name mismatch')
        for k, v in [('name', i['name']), ('mac', i['mac']), ('ip', (m.get('network') or {}).get('provisioning_ip'))]:
            if v:
                if v in seen[k]:
                    raise ValueError(f'Duplicate {k}: {v}')
                seen[k].add(v)
        machines.append(m)
    return machines


def render(machines, bindings):
    lines = ['# GENERATED BY GRAYSTONE AI FORGE - DO NOT EDIT', '']
    for m in machines:
        i = identity(m)
        ip = (m.get('network') or {}).get('provisioning_ip')
        if not i['mac'] or not ip:
            continue
        if i['loader'] == 'legacy':
            lines.append(f"dhcp-host={i['mac']},{ip},{i['name']},12h")
            continue
        b = bindings.get(i['name'])
        if not b or b.get('identity') != i:
            raise ValueError(f"{i['name']}: prepare and select a matching native Forge build before generating DHCP")
        digest = b.get('binary_sha256', '')
        if not re.fullmatch('[0-9a-f]{64}', digest):
            raise ValueError('Invalid native loader checksum')
        filename = f'ipxe-native-{digest}.efi'
        tag = 'forge-' + i['name']
        lines.extend([f"dhcp-host={i['mac']},set:forge-native,set:{tag},{ip},{i['name']},12h",
                      f'dhcp-boot=tag:efi64,tag:!ipxe,tag:{tag},{filename}'])
    return '\n'.join(lines) + '\n'


def bindings(root):
    import json
    p = root / 'config/pxe-loaders.json'
    return json.loads(p.read_text()) if p.exists() else {}


def write_generated(path, content):
    import os
    import tempfile
    path = Path(path)
    if path.is_symlink():
        raise ValueError('Refusing generated configuration symlink')
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp = tempfile.mkstemp(dir=path.parent)
    try:
        with os.fdopen(fd, 'w') as f:
            f.write(content)
            f.flush()
            os.fsync(f.fileno())
        os.chmod(temp, 0o644)
        os.replace(temp, path)
    finally:
        if os.path.exists(temp):
            os.unlink(temp)
